version: '3.8'
 
services:
  apigateway:
    image: audioappgateway
    build:
      context: .
      dockerfile: Audio.App/Audio.GateWay/Audio.ApiGateWay/Dockerfile
    ports:
      - "5000:80"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network
 
  identitymicroservice:
    image: audioappidentity
    build:
      context: .
      dockerfile: Audio.App/Audio.Identity/Presentation/IdentityWebApi/Dockerfile
    ports:
      - "5001:80"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network
 
  audiomicroservice:
    image: audioapp
    build:
      context: .
      dockerfile: Audio.App/Audio.WebApi/Presentation/AudioAppWebApi/Dockerfile
    ports:
      - "5002:80"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - app-network
 
networks:
  app-network:
    driver: bridge
