version: "3.9"

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: Audio.ApiGateWay3/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - DATABASE_CONNECTIONSTRING=Server=tcp:audioapp.database.windows.net,1433;Initial Catalog=AudioIdentityDB;User ID=Huseyn;Password=YourStrongPassword.123;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30; 
      # - DATABASE_CONNECTIONSTRING=Server=tcp:audioapp.database.windows.net,1433;Initial Catalog=AudioAppDB;User ID=Huseyn;Password=YourStrongPassword.123;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;         
    networks:
      - app-network

  identitymicroservice:
    image: audioappidentity
    build:
      context: .
      dockerfile: Audio.Identity/Presentation/IdentityWebApi/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_CONNECTIONSTRING=Server=tcp:audioapp.database.windows.net,1433;Initial Catalog=AudioIdentityDB;User ID=Huseyn;Password=YourStrongPassword.123;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;
    networks:
      - app-network

  audiomicroservice:
    image: audioapp
    build:
      context: .
      dockerfile: Audio.WebApi/Presentation/AudioAppWebApi/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_CONNECTIONSTRING=Server=tcp:audioapp.database.windows.net,1433;Initial Catalog=AudioAppDB;User ID=Huseyn;Password=YourStrongPassword.123;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30; 
    networks:
      - app-network

  react-app:
    build:
      context: .
      dockerfile: audioui/Dockerfile
    ports:
      - "3000:8080" # Map port 5000 on host to port 5000 in the container
    environment:
      - NODE_ENV=production
    volumes:
      - ./src:/app/src  # Optional: to enable live reloading during development
    command: npm run dev
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
