version: "3.9"

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: Audio.ApiGateWay3/Dockerfile
    ports:
      - "5004:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
    networks:
      - app-network

  identitymicroservice:
    image: audioappidentity
    build:
      context: .
      dockerfile: Audio.Identity/Presentation/IdentityWebApi/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_CONNECTIONSTRING=YOUR_CONNECTION_STRING
    networks:
      - app-network

  audiomicroservice:
    image: audioapp
    build:
      context: .
      dockerfile: Audio.WebApi/Presentation/AudioAppWebApi/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DATABASE_CONNECTIONSTRING=YOUR_CONNECTION_STRING 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
